corrigeaton_report:
    resource: "@CorrigeatonReportBundle/Controller/"
    type:     annotation
    prefix:   /admin/

corrigeaton_schedule:
    resource: "@CorrigeatonScheduleBundle/Controller/"
    type:     annotation
    prefix:   /admin/

