corrigeaton_mailer:
    resource: "@CorrigeatonMailerBundle/Controller/"
    type:     annotation
    prefix:   /

corrigeaton_schedule:
    resource: "@CorrigeatonScheduleBundle/Controller/"
    type:     annotation
    prefix:   /

