
security:
    firewalls:
        secured_area:
            pattern:    ^/admin
            anonymous: ~
            http_basic:
                realm: "Zone admin"

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        in_memory:
             memory:
                users:
                    admin: { password: f821ff6d562751a3d7a2a6f9d8b0bcfac6fd95f3, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User:
             algorithm:   sha1
             iterations: 1
             encode_as_base64: false
