<?php

namespace Corrigeaton\Bundle\ScheduleBundle\Entity\Repository;

use Corrigeaton\Bundle\ScheduleBundle\Entity\Teacher;
use Doctrine\ORM\EntityRepository;

/**
 * Repository/TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends EntityRepository
{
    public function countTest($isCorrected, Teacher $t=null)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('count(t)')
            ->from('CorrigeatonScheduleBundle:Test','t');

        if($isCorrected){
            $query->where('t.dateCorrected IS NOT NULL');
        }
        else
            $query->where('t.dateCorrected IS NULL');

        if(!empty($t)){
            $query->andWhere('t.teacher = :teacher')
                ->setParameter('teacher',$t);
        }

        return $query
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findByCorrected($isCorrected)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                      ->select('t')
                      ->from("CorrigeatonScheduleBundle:Test", "t");

        if($isCorrected)
        {
            $query->where("t.dateCorrected IS NOT NULL");
        } else {
            $query->where("t.dateCorrected IS NULL");
        }

        return $query->getQuery()->getResult();
    }

}
