<?php

namespace Corrigeaton\Bundle\ScheduleBundle\Entity\Repository;

use Corrigeaton\Bundle\ScheduleBundle\Entity\Teacher;
use Doctrine\ORM\EntityRepository;

/**
 * Repository/TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends EntityRepository
{
    public function countNameTestTeacherStatus(Teacher $t, $status)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('count(t)')
            ->from('CorrigeatonScheduleBundle:Test','t')
            ->where('t.status = :status')
            ->andWhere('t.teacher = :teacher')
            ->setParameter('teacher',$t)
            ->setParameter('status',$status)
            ->getQuery()
            ->getSingleScalarResult();
    }

}
